language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - pypy
    - pypy3

install:
 - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install importlib unittest2; fi
 - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install --install-option='--no-cython-compile' cython ; fi
 - pip install 'coverage<4'
 - pip install coveralls

script:
 - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then python setup.py build_ext --inplace ; fi
 # PyPy is way to slow with coverage at the moment of this writing, so better avoid coverage when using PyPy
 - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]] ; then nosetests -vv --with-coverage ; else nosetests -vv ; fi

after_success:
    coveralls

notifications:
    email:
        on_success: change
        on_failure: change

# PyPy can fail because of Cython - but this should not anymore since the related unit tests are now directly skipped if running under PyPy
#matrix:
#  allow_failures:
#    - python: pypy
#    - python: pypy3
